admins:
- nitishkumar3012
forwards:
- source: -1001179926082
  dest:
  - -727391052
  offset: 3079
  end: 0
- source: -1001422786409
  dest:
  - -773608275
  offset: 2885
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 0.0
plugins: {}
